### PR TITLE
upgrade pict-rs to 0.4.2

### PR DESCRIPTION
**Pull request by MarsAgainstVenus**
Update pict-rs to  0.4.2
Increment LED

I've been testing this for a little bit and everything seems to be running just fine.

### CODE REVIEW

**Comment by ubergeek77** [comment]
Hey there, thanks for the PR!

I really do appreciate you working to upgrade and test this. But as a rule, I like to keep parity with the "official" Lemmy deployment, which currently still uses `0.4.0`:

https://github.com/LemmyNet/lemmy-ansible/blob/a95c3321c3611ab0616dae361ded35c21b9da206/templates/docker-compose.yml#L52

However, I will leave this PR open for now. If Lemmy `0.18.5` rolls by and they *still* haven't upgraded their pict-rs version, and your own server doesn't have any issues running `0.4.2`, (I can't imagine it would), I'll go ahead and accept this version change :)

**Comment by MarsAgainstVenus** [comment]
No worries! I didn't realize the official was still on 0.4.0. I was mainly interested in the new timeout feature in hopes that it would help my free tier Google Cloud instance stop freezing up!

I am in the Matrix chat linked on join-lemmy.org and it seems some of the bigger instances have migrated to 0.4.2 successfully, including Lemm.ee.

And no rush in accepting this pull request. I just knew you said you were busy yesterday so thought I'd contribute what little I could!

**Comment by ubergeek77** [comment]
Turns out Lemmy is using 0.4.3 now!

**Comment by MarsAgainstVenus** [comment]
Even better!

**Pull request closed without merging**
